#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/scripts/theme" || exit

# brown for text and y/n | cyan for questions | green for responses | pink for command type stuff
echo ""
echo -e "${BROWN} Hi user${RESET}"

echo ""
sleep 1
echo -e "${BROWN} This will allow you to take care of my virtual cat Pixel with me!${RESET}"

# CRON

echo ""
sleep 1
echo -e "${CYAN} I want to automatically pull updates from my github every 30 mins ${RESET}${PINK}(cron)${RESET}"
echo ""
sleep 1
read -p "$(echo -e "${CYAN} Is that ok? ${RESET}${BROWN} (y/n) ${RESET}")" answer
echo ""
# > user says y to cron?
    # > y
    if [[ $answer == "y" ]]; then
        # >> does crontab exist?
        # >> y
        if command -v crontab &>/dev/null; then
            (crontab -l 2>/dev/null; echo "*/30 * * * * cd $SCRIPT_DIR && git pull") | crontab -
            echo -e "${GREEN} > Yay! I'll stay up to date ᓚ₍ ^. .^₎${RESET}"
        # >> n
        else
            echo -e "${GREEN} > Auto-updates aren't supported on your system${RESET}"
            echo -e "${GREEN} > You can manually update with:${RESET}"
            echo -e "${PINK}   cd $SCRIPT_DIR && git pull${RESET}"
            echo ""
            sleep 1
            echo -e "${CYAN} Since you have to do it manually, I can add the alias ${RESET}${PINK}pixelUpdate ${RESET}${CYAN}that does what is written above ${PINK}(bashrc)${RESET}"
            echo ""
            sleep 1
            read -p "$(echo -e "${CYAN} Is that ok? ${RESET}${BROWN} (y/n) ${RESET}")" answer
            # >>> user says yes to alias>
            # >>> y
                if [[ $answer == "y" ]]; then
                    echo "alias pixelUpdate=\"cd $SCRIPT_DIR && git pull\"" >> ~/.bashrc
                    echo -e "${GREEN} > AFTER setup run ${RESET}${PINK}source ~/.bashrc${RESET}${GREEN} OR open a new terminal to activate commands!${RESET}"
                fi
            # >>> n : nothing
        fi
    # > n
    else
        echo -e "${GREEN} > You can manually update with:${RESET}"
        echo -e "${PINK}   cd $SCRIPT_DIR && git pull${RESET}"
    fi

# ALIASES
echo ""
sleep 1
echo -e "${CYAN} I want to add these aliases to your terminal to make shorter commands ${RESET}${PINK}(bashrc)${RESET}"
echo -e "${PINK} virtualPet | clean | explore | feed | fish | pat | play | rest | train ${RESET}"
echo ""
sleep 1
read -p "$(echo -e "${CYAN} Is that ok? ${RESET}${BROWN} (y/n) ${RESET}")" answer
echo ""
    chmod +x "$SCRIPT_DIR"/scripts/* #scripts always executable
    if [[ $answer == "y" ]]; then
        echo "alias virtualPet=\"$SCRIPT_DIR/scripts/virtualPet\"" >> ~/.bashrc
        echo "alias clean=\"$SCRIPT_DIR/scripts/clean\"" >> ~/.bashrc
        echo "alias explore=\"$SCRIPT_DIR/scripts/explore\"" >> ~/.bashrc
        echo "alias feed=\"$SCRIPT_DIR/scripts/feed\"" >> ~/.bashrc
        echo "alias fish=\"$SCRIPT_DIR/scripts/fish\"" >> ~/.bashrc
        echo "alias pat=\"$SCRIPT_DIR/scripts/pat\"" >> ~/.bashrc
        echo "alias play=\"$SCRIPT_DIR/scripts/play\"" >> ~/.bashrc
        echo "alias rest=\"$SCRIPT_DIR/scripts/rest\"" >> ~/.bashrc
        echo "alias train=\"$SCRIPT_DIR/scripts/train\"" >> ~/.bashrc

        echo ""
        echo -e "${GREEN} > Run ${RESET}${PINK}source ~/.bashrc${RESET}${GREEN} OR open a new terminal to activate commands!${RESET}"
        echo -e "${GREEN} > Then type${RESET}${BOLD}${PINK} virtualPet${RESET}${GREEN} to get started ${RESET}"

    else
        echo -e "${GREEN} > You can still play by running commands manually. Reference the main page${RESET}"
        echo -e "${GREEN} > Main page: ${RESET}"
        echo -e "${PINK}   bash $SCRIPT_DIR/scripts/virtualPet${RESET}"
        echo ""
    fi




