#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/theme" || exit

curl -s -X POST https://virtualPet.mimobox.sh/clean > /dev/null


messages=(
  " ${PINK}Nice and clean!${RESET}"
  " ${PINK}✧✧/ᐠ-ꞈ-ᐟ\✧✧ *Shiny*${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"