#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/theme" || exit

if ! curl -s -X POST https://virtualPet.mimobox.sh/fish > /dev/null; then
  echo " ${PINK}Pixel can't reach the server right now :(${RESET}"
  exit 1
fi


messages=(
  " ${PINK}>-;;€ᐷ${RESET}"
  " ${PINK}<•)))))><${RESET}"
  " ${PINK}<◉ )))><<${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"