#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/theme" || exit

curl -s -X POST https://virtualPet.mimobox.sh/fish > /dev/null

messages=(
  " ${PINK}>-;;€ᐷ${RESET}"
  " ${PINK}<•)))))><${RESET}"
  " ${PINK}<◉ )))><<${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"