#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/theme" || exit

if ! curl -s -X POST https://virtualPet.mimobox.sh/play > /dev/null; then
  echo " ${PINK}Pixel can't reach the server right now :(${RESET}"
  exit 1
fi



messages=(
  " ${PINK} You throw a ball of yarn at Pixel${RESET}"
  " ${PINK} Pixel challenged you to thumb war... somehow...${RESET}"
  " ${PINK} ᓚᘏᕐᐷ You throw a toy mouse at Pixel${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"