#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/theme" || exit

if ! curl -s -X POST https://virtualPet.mimobox.sh/rest > /dev/null; then
  echo " ${PINK}Pixel can't reach the server right now :(${RESET}"
  exit 1
fi


messages=(
  " ${PINK} You've tucked Pixel in!${RESET}"
  " ${PINK} Honk mimimimi${RESET}"
  " ${PINK} Pixel is drooling!${RESET}"
)

echo "${messages[$RANDOM % ${#messages[@]}]}"